import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Dashboard from './_components/ui/dashboard/Dashboard'
import AddToAlbumDialog from './_components/ui/add-album/add-to-album-dialog'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Photo Album',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Dashboard>{children}</Dashboard>
        <AddToAlbumDialog />
      </body>
    </html>
  )
}
